<a href="https://colab.research.google.com/github/arashfahim/Deep-Schemes-for-Control/blob/main/Dr_Fahim_Second_Approach_(10_Dimensions).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from google.colab import drive,files
# drive.mount('/content/gdrive')


# Importing

In [ ]:
import numpy as np
from scipy import misc
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
%matplotlib inline
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR, CyclicLR, ReduceLROnPlateau, LinearLR, ExponentialLR
import random
from torch.autograd.functional import jacobian, hessian
# import AUTOGRAD.FUNCTIONAL.JACOBIAN as jacobian
import time
import math

import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
mpl.rcParams['legend.fontsize'] = 10

# Hyperparameters

In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
num_sample=torch.tensor([600000]).to(device) #M
# dim=torch.tensor([3]).to(device)          #D
num_time_interval=torch.tensor([10]).to(device)    #N
# T=torch.tensor([1]).to(device)
T=1
# T=torch.tensor([1])
delta_t = torch.tensor(T/ num_time_interval).to(device)
# t_steps = torch.linspace(0,1,num_time_interval).to(device)
# sqrt_delta_t = torch.sqrt(delta_t).to(device)
# sqrt_delta_t = torch.sqrt(delta_t).to(device)
sqrt_delta_t = torch.sqrt(delta_t).to(device)
# x_init = torch.zeros(dim)
# sigma=torch.sqrt(torch.tensor([2.0]))
# lamb=torch.tensor([1.0]).to(device)
mu=torch.tensor([1.0]).to(device)
sigma=torch.tensor([1.0]).to(device)
alpha=torch.tensor([1.0]).to(device)
start = torch.tensor([0]).to(device)
end = torch.tensor([1]).to(device)
num_steps=5
num_ite=int(num_time_interval/num_steps)
# kappa=torch.tensor([1]).to(device)
# theta=torch.tensor([0.4]).to(device)
# nu=torch.tensor([0.5]).to(device)
# lamb=torch.tensor([0.6]).to(device)
# eta=torch.tensor([0.5]).to(device)
p=torch.tensor([0.95]).to(device)
# rho=torch.tensor([0]).to(device)
num_runs=1
# x0=torch.ones([1,dim]).to(device)+4
# print(x0)

t_steps = torch.linspace(0,T,num_time_interval.item()+1).to(device)
print(t_steps)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000], device='cuda:0')


<ipython-input-23-4fab70f4d414>:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  delta_t = torch.tensor(T/ num_time_interval).to(device)


##$n=1  \quad (d=2)$

In [ ]:
#dim=torch.tensor([2]).to(device)
#kappa=torch.tensor([1]).to(device)
# theta=torch.tensor([0.4]).to(device)
# nu=torch.tensor([0.2]).to(device)
# lamb=torch.tensor([1.5]).to(device)
# eta=torch.tensor([0.5]).to(device)
# rho=torch.tensor([0.0]).to(device)

##$n=2 \quad (d=3)$


In [ ]:
# dim=torch.tensor([3]).to(device)
# kappa=torch.tensor([1, 0.8]).to(device)
# theta=torch.tensor([0.1,0.2]).to(device)
# nu=torch.tensor([0.2, 0.15]).to(device)
# lamb=torch.tensor([0.1, 0.2]).to(device)

# # lamb=torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.4, 0.3,0.2,0.1]).to(device)


# eta=torch.tensor([0.5]).to(device)
# rho=torch.tensor([0.0, 0.0]).to(device)

##$n=4 \quad (d=5) $

In [ ]:
# dim=torch.tensor([5]).to(device)
# kappa=torch.tensor([1, 0.8, 1.1 ,1.3]).to(device)
# theta=torch.tensor([0.1,0.2,0.3,0.4]).to(device)
# nu=torch.tensor([0.2, 0.15, 0.25, 0.31]).to(device)
# lamb=torch.tensor([0.1, 0.2, 0.3,0.4]).to(device)



# # lamb=torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.4, 0.3,0.2,0.1]).to(device)
# eta=torch.tensor([0.5]).to(device)
# rho=torch.tensor([0.0, 0.0, 0.0, 0.0]).to(device)

##$n=9 \quad (d=10)$

In [ ]:
dim=torch.tensor([10]).to(device)
kappa=torch.tensor([1, 0.8,1.1, 1.3, 0.95, 0.99,1.02, 1.06, 1.6]).to(device)
theta=torch.tensor([0.1, 0.2, 0.3, 0.4, 0.25, 0.15, 0.18, 0.08, 0.91]).to(device)
nu=torch.tensor([0.2, 0.15, 0.25, 0.2, 0.2, 0.1, 0.22, 0.2, 0.15]).to(device)
# lamb=torch.tensor([1.5, 1.1, 2, 0.8, 0.5, 1.7, 0.9, 1, 0.9]).to(device)

lamb=torch.tensor([0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4,0.45,0.5]).to(device)

# # lamb=torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.4, 0.3,0.2,0.1]).to(device)

eta=torch.tensor([0.5]).to(device)
rho=torch.tensor([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]).to(device)

In [ ]:
def H(x,z,gamma): #### out_shape =([M]) |  input:  x_shape=[M,D,1],  z shape = [M,D,1],gamma shape= [M,dim,dim]
  result=torch.zeros([x.shape[0]]).to(device)
  for i in range(dim-1):
    result+=kappa[i]*(theta[i]-x[:,i+1,0])*z[:,i+1,0]+0.5*torch.pow(nu[i],2)*gamma[:,i+1,i+1]-rho[i]*lamb[i]*nu[i]*(z[:,0,0]*gamma[:,0,i+1])/gamma[:,0,0] \
    + 0.5*torch.pow(rho[i]*nu[i]*gamma[:,0,i+1],2)/gamma[:,0,0]
    # print(result)
  result1=result-0.5*torch.sum(torch.square(lamb))*torch.pow(z[:,0,0],2)/gamma[:,0,0]
  return result1

In [ ]:
def F(x,z,a): #### out_shape =([M]) |  input:  x_shape=[M,D,1],  z shape = [M,D,1],a_shape= [M,D,D]  #This is for rho=0
  result=torch.zeros([x.shape[0]]).to(device)
  for i in range(dim-1):
    result+=-kappa[i]*(theta[i]-x[:,i+1,0])*z[:,i+1,0]
    # print(result)
  result1=result-torch.sqrt(torch.sum(torch.square(lamb)))*torch.abs(z[:,0,0])*torch.sqrt(a[:,0,0])
  return result1

# Functions

In [ ]:
def g1(x): #out_shape= [M,1,1]   | input:  x_shape=[M,D,1]
  result=1-torch.exp(-eta*x[:,0])
  result=torch.reshape(result,(result.shape[0],1,1))
  return result

def update(data,delta_w,L):#output: data=(M,D,1) ,  #input data=(M,D,1), delta_w=[M,D,1]
    dx = torch.bmm(L,delta_w)
    data = data + dx
    data=data
    return data

def der1(x,f):  #output= [M,D,1], input: x=[M,D,1]
  Du=torch.zeros(x.shape[0],dim).to(device)
  xin=x.clone().detach()
  xin.requires_grad=True
  u=f(xin)
  print(u)
  print('u shape', u.shape)
  Du=torch.autograd.grad(outputs=[u],inputs=[xin],grad_outputs=torch.ones_like(u),
                          allow_unused=True,retain_graph=True,create_graph=True)[0]
  print('Du shape', Du.shape)
  Du=torch.reshape(Du,(Du.shape[0],dim,1))
  print('Du shape', Du.shape)
  return Du


def grad_hessian1(x,f_,c=False): #output= [M,D,D], #input: x=[M,D,1]   #c=False => data=[M,D]   #c=True =>data=[M,D,1]
    hess_temp=torch.zeros(x.shape[0],dim,dim).to(device)
    Du=torch.zeros(x.shape[0],dim).to(device)

    if c==False:
      # xin=x.unsqueeze(2).clone().detach()
      xin=x.clone().detach()
      xin.requires_grad=True
      # print(xin.shape)
      # xin.requires_grad=True
      u=f_(xin).squeeze(2)
      # print(u.shape)
      # xin=xin.unsqueeze(2)
      # print(xin.shape)
      Du=torch.autograd.grad(outputs=[u],inputs=[xin],grad_outputs=torch.ones_like(u),
                           allow_unused=True,retain_graph=True,create_graph=True)[0].unsqueeze(2)
      hess_temp= torch.cat([ torch.autograd.grad(outputs=[Du[:,i,:]],inputs=[xin],grad_outputs=torch.ones_like(Du[:,i,:]),
                           allow_unused=True,retain_graph=True,create_graph=True)[0] for i in range(dim)],1)
    else:
      xin=x.clone().detach()
      xin.requires_grad=True
      u=f_(xin.squeeze(2))
    # print("xin shape: ",xin.shape)
      Du=torch.autograd.grad(outputs=[u],inputs=[xin],grad_outputs=torch.ones_like(u),
                           allow_unused=True,retain_graph=True,create_graph=True)[0]
    # print("Du shape:",Du.shape)
    # print("-----")
    # print(torch.autograd.grad(outputs=[Du[:,0,:]],inputs=[xin],grad_outputs=torch.ones_like(Du[:,0,:]),
    #                        allow_unused=True,retain_graph=True,create_graph=True)[0].shape)
      hess_temp= torch.cat([ torch.autograd.grad(outputs=[Du[:,i,:]],inputs=[xin],grad_outputs=torch.ones_like(Du[:,i,:]),
                           allow_unused=True,retain_graph=True,create_graph=True)[0] for i in range(dim)],1)
    # print("D2u shape:",hess_temp.shape)
    Du = torch.reshape(Du,(Du.shape[0],dim,1))
    # print("Du shape:",Du.shape)
    hess_temp=torch.reshape(hess_temp,(hess_temp.shape[0],dim,dim))
    # print("D2u shape:",hess_temp.shape)

    # print(hess_temp)
    return Du, hess_temp
def hessian1(x,model2z):  #x=[M,D,1]  output= [M,D,1]
    hess_temp=torch.zeros(x.shape[0],dim,dim).to(device)
    # print("D2u shape:",hess_temp.shape)

    Du=torch.zeros(x.shape[0],dim).to(device)
    xin=x.clone().detach()
    # print('this is xin')
    # print(xin)
    xin.requires_grad=True
    Du = model2z(xin.squeeze(2))
    # print('this is Du')
    # print(Du)
    # print('this is Du shape')
    # print(Du.shape)
    # print('this is Du 1')
    # print(Du[:,1,:])
    hess_temp= torch.cat([ torch.autograd.grad(outputs=[Du[:,i,:]],inputs=[xin],grad_outputs=torch.ones_like(Du[:,i,:]),
                           allow_unused=True,retain_graph=True,create_graph=True)[0] for i in range(dim)],1)

    # print("D2u shape:",hess_temp.shape)

    hess_temp=torch.reshape(hess_temp,(hess_temp.shape[0],dim,dim))

    # print(hess_temp)
    return hess_temp
def L_matrix(ite,x,model):  #x=[M,D]
  L=torch.zeros(x.shape[0],dim,dim).to(device)

  L[:,0,0]=model[ite](x)
  for i in range(dim-1):
    L[:,i+1,i+1]=nu[i]
  return L
def opt_quad():
  return torch.pow(torch.sum(torch.pow(lamb,2)),0.5)/eta

def L_matrix_test(ite,x,model1):  #This matrix is a matrix with L00 = 0.6 and L11=nu
  L=torch.zeros(x.shape[0],dim,dim)
  L[:,0,0]=opt_quad()
  for i in range(dim-1):
    L[:,i+1,i+1]=nu[i]
  return L

In [ ]:
def sample(ite): #output: [M,D]  #input: a scalar
    # x=(torch.rand(num_sample,1))
    # delta_w=torch.rand(num_sample,dim).to(device)*delta_t
    # x=(torch.rand(num_sample,1))
    if ite==num_ite:
      x=(start_list[ite-1])+(end_list[ite-1]-start_list[ite-1])*torch.rand(num_sample,dim)
      # x=(start_list[ite])+(end_list[ite]-start_list[ite])*delta_w
    else:
      x=(start_list[ite-1])+((end_list[ite-1])-(start_list[ite-1]))*torch.rand(num_sample,dim)
    return x

In [ ]:
def gradient(x,f): #input=  [M,D,1]    #output= [M,D,1]
  xin=x.clone().detach()
  xin.requires_grad=True
  u=f(xin.squeeze(2));
  Du=torch.autograd.grad(outputs=[u],inputs=[xin],grad_outputs=torch.ones_like(u),allow_unused=True,retain_graph=True,create_graph=True)[0]
  return Du

# Generating Data

## List of Intervals

In [ ]:
# start_list=[2.5,2,1.5,1,0.5,0]
# end_list=[3.5,4,4.5,5,5.5,6]

# start_list=[10,5,0]
# end_list=[12,17,22]
# start_list=[10,5,0]
# end_list=[12,17,22]

# start_list=[3,1,-1]
# end_list=[5,7,9]


# start_list=[2,1,0]
# end_list=[4,5,6]

# start_list=[16,8,0]
# end_list=[18,26,34]

# start_list=[-1,-3,-5]
# end_list=[1,3,5]


# start_list=[3,1.5,0]
# end_list=[5,6.5,8]

start_list=[4,2,0]
end_list=[6,8,10]

In [ ]:
#M = number of samples
#D = number of dimension
#N = num_time_interval

# delta_w=sqrt_delta_t.cpu()*torch.randn(num_sample,dim,num_time_interval)   #[M,D,N]

# print(delta_w.shape)


In [ ]:
def remove_outliers(ite,x):
    path_min = torch.min(x.flatten(start_dim=1), dim=1)[0]
    # print(path_min)
    path_max = torch.max(x.flatten(start_dim=1), dim=1)[0]
    # print(path_max)
    pick_sample = torch.logical_and(path_max < end_list[ite],path_min > start_list[ite])
    # print(pick_sample)
    x_new=x[pick_sample,:]
    # print('the percent of paths removed is {}%'.format((x.shape[0]-x_new.shape[0])/(x.shape[0])*100))
    return x_new

In [ ]:
def data_generator2(ite,t1,t2,delta_w): #input: ite=scalar, t1=scalar, t2=scalar     #output: [M,D,1]
  count=0
  l=[]
  k=[]
  # start_=start_list[ite-1]
  # print(start_)
  # end_=end_list[ite-1]
  xx=torch.zeros([num_sample,dim,num_time_interval+1]).to(device)
  # xx=torch.zeros([num_sample,dim,t2-t1+2]).to(device)
  # xx[:,:,t1]=start_list[ite-1]+(end_list[ite-1]-start_list[ite-1])*(torch.rand(num_sample,dim))
  xx[:,:,t1]=start_list[ite-1]+(end_list[ite-1]-start_list[ite-1])*delta_w[:,:,t1-1]

  # if ite==num_ite:
  for i in range(t1, t2+1):
    L=L_matrix(ite-1,xx[:,:,i].to(device),model1)
    # L=L_matrix_test(ite-1,xx[:,:,i].to(device),model1)
    # print(L)
    xx[:,:,i+1]=(xx[:,:,i]+torch.bmm(L,delta_w[:,:,i].unsqueeze(2)).squeeze(2)).clone().detach()
  path_min = torch.min(xx[:,:,t1:t2+2].flatten(start_dim=1), dim=1)[0]
  # print(path_min)
  path_max = torch.max(xx[:,:,t1:t2+2].flatten(start_dim=1), dim=1)[0]
  # print(path_max)
  pick_sample = torch.logical_and(path_max < end_list[ite],path_min > start_list[ite])
  # print(pick_sample)
  xx_new=xx[pick_sample,:,:]
  delta_w_new=delta_w[pick_sample,:,:]

  return xx_new.cpu(),delta_w_new.cpu()
  # return xx.cpu(),delta_w

# Initilizing Model 1

In [ ]:
class ann1(nn.Module):
    # def __init__(self):
        # super(ann1, self).__init__()
        # self.linear_stack = nn.Sequential(
        #     nn.Linear(dim, 128),
        #     nn.LogSigmoid(),
        #     nn.Linear(128, 128),
        #     nn.LogSigmoid(),
        #     nn.Linear(128, 128),
        #     nn.LogSigmoid(),
        #     nn.Linear(128, 1),
        #     nn.LogSigmoid(),
        #     # nn.ReLU()
        # )
    def __init__(self):
        super(ann1, self).__init__()
        self.linear_stack = nn.Sequential(

            nn.Linear(dim, 256),
            # nn.BatchNorm1d(256),
            nn.Tanh(),
            nn.Linear(256,256),
            # nn.BatchNorm1d(256),
            nn.Tanh(),
            # nn.Linear(256,256),
            # nn.Tanh(),
            nn.Linear(256, 128),
            # nn.BatchNorm1d(128),
            nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            nn.Linear(128,1),
        )
    def forward(self, x):
        logits = self.linear_stack(x)
        logits=torch.reshape(logits,(x.shape[0],))
        # logits=torch.flatten(logits)
        # logits=torch.reshape(logits,[x.shape[0]])
        # logits=nn.ELU()(logits)+1.5
        # logits=torch.reshape(logits,(x.shape[0],1,1))
        return torch.max(logits,-logits)

In [ ]:
model1= nn.ModuleList([ann1() for i in range(num_ite)]).to(device)

In [ ]:
print(torch.mean(model1[0](torch.ones(100,dim).to(device))))

tensor(0.0440, device='cuda:0', grad_fn=<MeanBackward0>)


# Loss function 1

In [ ]:
######## TEST#######################

def loss_fn1(ite,x,delta_w,model):  #x=[M,D,1]  delta_w = [M,D,1]
    L=torch.zeros(x.shape[0],dim,dim).to(device)
    L[:,0,0]=model(x.squeeze(2))
    for i in range(dim-1):
      L[:,i+1,i+1]=nu[i]
    n=update(x,delta_w,L)
    if ite==num_ite:
      Y=g1(n).to(device)
      # print(Y.shape)
      # print("Y= ")
      # print(Y)
      Z,hessian=grad_hessian1(n,g1)
      # print("Z= ")
      # print(Z)
      # print("Hessian= ")
      # print(hessian)
    else:
      n=remove_outliers(ite,n)
      L=L[0:n.shape[0],:,:]
      Y=modely2[t2+1](n.squeeze(2))
      Z,hessian=grad_hessian1(n.squeeze(2),modely2[t2+1])
      Z=Z+0.0001
      hessian=hessian+0.0001
      # print("Z= ", Z)
      # print("hessian= ",hessian)
    LTL=torch.bmm(torch.transpose(L,1,2),L)
    # print("LTL =", LTL)
    LTLhessian=torch.bmm(LTL,hessian)
    # print("LTLhessian =", LTLhessian)
    Tr=LTLhessian.diagonal(offset=0,dim1=-1,dim2=-2).sum(-1)
    # print("Trace =", Tr)
    H_=H(n,Z,hessian)
    # print("H = ", H_)
    F_=F(n,Z,LTL)
    # print("F= ", F_)
    # loss=torch.mean(torch.pow(H_-0.5*Tr+F_,2))
    loss=torch.mean(torch.pow(H_-0.5*Tr+F_,2))
    return loss


# Initializing Model 2

In [ ]:
class anny2(nn.Module): #input [M,D], #output [M,1,1]
    def __init__(self):
        super(anny2, self).__init__()
        self.linear_stack = nn.Sequential(
            nn.Linear(dim, 128),
            nn.Tanh(),
            nn.Linear(128,256),
            nn.Tanh(),
            # nn.Linear(256, 256),
            # nn.Tanh(),
            # nn.Linear(256,256),
            # nn.Tanh(),
            # nn.Linear(256,256),
            # nn.Tanh(),
            nn.Linear(256,128),
            nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            nn.Linear(128,1),

        )
    def forward(self, x):
        logits = self.linear_stack(x)

        logits=torch.reshape(logits,(x.shape[0],1,1))
        return logits
        # return torch.min(logits,-logits)

class annz2(nn.Module): #input [M,D], #output [M,D,1]
    def __init__(self):
        super(annz2, self).__init__()
        self.linear_stack = nn.Sequential(
            nn.Linear(dim, 128),
            nn.Tanh(),
            nn.Linear(128,256),
            nn.Tanh(),
            nn.Linear(256, 256),
            nn.Tanh(),
            nn.Linear(256,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            # nn.Linear(128,128),
            # nn.Tanh(),
            nn.Linear(128,dim),
            # nn.ReLU(),
        )
    def forward(self, x):
        logits = self.linear_stack(x)

        logits=torch.reshape(logits,(x.shape[0],dim,1))
        return logits
        # return torch.min(logits,-logits)

In [ ]:
modely= anny2().to(device)
modelz= annz2().to(device)
modely2= nn.ModuleList([anny2() for i in range(num_time_interval+1)]).to(device)
modelz2= nn.ModuleList([annz2() for i in range(num_time_interval+1)]).to(device)

# Loss Function 2

In [ ]:
def loss_fn2(ite,data,delta_w):

  bb=L_matrix(ite-1,data[:,:,t1],model1).to(device)
  ss=torch.pow(bb,2)
  loss=0
  Y=modely2[t1](data[:,:,t1])
  # print(data[:,:,t1].shape)
  # gradY,hessianY=grad_hessian1(data[:,:,t1],modely2[t1])
  Z=gradient(data[:,:,t1].unsqueeze(2),modely2[t1]).to(device)



  for i in range(t1,t2):
    Y=Y.flatten()+F(data[:,:,i].unsqueeze(2),Z,ss)*delta_t+torch.bmm(torch.bmm(torch.transpose(Z,1,2),bb),delta_w[:,:,i].unsqueeze(2)).flatten()
    bb=L_matrix(ite-1,data[:,:,i+1],model1).to(device)
    # bb=L_matrix_test(ite-1,data[:,:,i+1],model1).to(device)
    ss=torch.pow(bb,2)
    # Z=modelz2[i+1](data[:,:,i+1])
    Z=gradient(data[:,:,i+1].unsqueeze(2),modely2[i+1])
    # loss+=torch.mean(torch.mean(torch.square(gradient(data[:,:,i+1].unsqueeze(2),Y)-Z).squeeze(2),1))
  Y=Y.flatten()+F(data[:,:,t2].unsqueeze(2),Z,ss)*delta_t+torch.bmm(torch.bmm(torch.transpose(Z,1,2),bb),delta_w[:,:,t2].unsqueeze(2)).flatten()


  if ite==num_ite:

    loss+=torch.mean(torch.square(Y-g1(data[:,:,t2+1]).flatten()))

  else:

    loss+=torch.mean(torch.square(Y-modely2[t2+1](data[:,:,t2+1]).flatten()))
  return loss


#Training Both Model1 And Model2 Simultaneously

In [ ]:
from IPython.core.pylabtools import figsize
batch_size=64*2*2*2*2
num_epoch1 =200
num_epoch2=200
total_batch=int((num_sample/batch_size))
index=0
last_loss1 = 0
last_loss2=0
loss_delta1 = 0
loss_delta2=0
loss_treshold1 = 0
loss_treshold2=0
loss_tmp1=[]
loss_tmp2=[]
# my_index=torch.arange(num_sample)

In [ ]:
print(batch_size)

1024


# Optimizer 1

In [ ]:
# lr1=[0.1, 0.1, 0.1, 0.1, 0.1]
# lr1=[0.000000015, 0.05, 0.01, 0.01, 0.01]
lr1=[0.00005, 0.00001, 0.0005, 0.0005, 0.0005]
def opt1(ite):
  l=[]
  lr_=lr1[ite]
  # optimizer=optim.SGD(model1[ite-1].parameters(), lr=lr_, momentum=0.9)
  optimizer=optim.Adam(model1[ite-1].parameters(),lr=0.000005)
  # optimizer=optim.Adam(model1[ite-1].parameters(),lr=lr_,weight_decay=1e-5)
  scheduler = ExponentialLR(optimizer, gamma =0.9)
  # optimizer = torch.optim.Adam(model1[ite-1].parameters(), lr=lr_, weight_decay=1e-5)

  return optimizer

#Optimizer 2

In [ ]:
# lr2=[0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
# lr2=[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
# lr2=[0.015, 0.015, 0.015, 0.015, 0.015, 0.015, 0.015,0.015, 0.015, 0.015, 0.015, 0.015, 0.015]
lr2=[0.000001, 0.000001, 0.0001, 0.00001, 0.00001, 0.00001, 0.00001,0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]
def opt2(ite,t1,t2):
  l=[]
  lr_=lr2[ite]

  # for i in range(t1,t2+1):
  #   l+=list(modely2[i].parameters())+list(modelz2[i].parameters())

  # l=list(modely2[t1].parameters())
  for i in range(t1,t2+1):
    l+=list(modely2[i].parameters())
  # optimizer=optim.Adam(l,lr=0.005)
  optimizer=optim.SGD(l, lr=lr_, momentum=0.9)
  # optimizer = torch.optim.Adam(l, lr=lr_, weight_decay=1e-5)
  scheduler = ExponentialLR(optimizer, gamma =0.9)
  return optimizer

# Value function
$u(t,x,v)=-e^{-\eta x-0.5(T-t)\lambda^2}$

In [ ]:
def V1(t,x):
  result=1-torch.exp(-eta*x-0.5*(T-t)*torch.sum(torch.pow(lamb,2))).to(device)
  return result

In [ ]:
#### TESTTTTTTTTTT ##################
t1 = time.time()
model1results=[]
modely2results=[]
modelz2results=[]
for i in range(1): #numer of runs
  # model1= nn.ModuleList([ann1() for i in range(num_ite)]).to(device)
  # modely2= nn.ModuleList([anny2() for i in range(num_time_interval+1)]).to(device)
  # modelz2= nn.ModuleList([annz2() for i in range(num_time_interval+1)]).to(device)
  print("This is {}th run".format(i+1))
  # delta_w1 = torch.randn(size=[num_sample, dim]).to(device) * sqrt_delta_t
  for ite in range(num_ite,0,-1):
    # model1results=[]
    # modely2results=[]
    # modelz2results=[]
    t_0 = time.time()
    x0=torch.ones([1,dim]).to(device)+start_list[ite-1]
    x01=torch.ones([100,dim]).to(device)+start_list[ite-1]
    print(x0)
    print("At iteration {}:".format( ite))
    t1=ite*num_steps-num_steps
    print(t1)
    t2=ite*num_steps-1
    print(t2)
    optimizer_1=opt1(ite)
    # if ite==num_ite:
    #   num_epoch1=150
    # else:
    #   num_epoch1=150
    # num_epoch1=0
    delta_w = torch.randn(size=[num_sample, dim]).to(device) * sqrt_delta_t
    for epoch in range(num_epoch1):

      # delta_w = torch.randn(size=[num_sample, dim]).to(device) * sqrt_delta_t
      data=sample(ite)
      my_index1=torch.arange(data.shape[0])
      total_batch1=int((data.shape[0]/batch_size))
      t_1=time.time()
      for batch in range(total_batch1):
        if batch==total_batch1-1:
              temp_index=my_index1[batch*batch_size : ]
        else:
              temp_index=my_index1[batch*batch_size : batch*batch_size + batch_size]

        optimizer_1.zero_grad()
        # loss1=loss_fn1(ite,data.unsqueeze(2)[temp_index,:].to(device),delta_w[temp_index,:,t2].unsqueeze(2).to(device),model1[ite-1])
        loss1=loss_fn1(ite,data.unsqueeze(2)[temp_index,:].to(device),delta_w[temp_index,:].unsqueeze(2).to(device),model1[ite-1])
        loss1.backward()
        optimizer_1.step()
      loss_tmp1.append(loss1.item())
      loss_delta1 = loss1.item() - last_loss1
      last_loss1 = loss1.item()
      if epoch %10 == 0:
        print("Loss function 1 at epoch {:.0f} is {:.12e}  |  Loss delta: {}   |    Training time: {:.5f}s".format(index*(num_epoch1)+epoch, loss_delta1,loss1.item(), time.time()-t_1))
        # print("Total time for training {:.0f} epochs is {:.4e}s".format(index*(num_epoch1)+epoch+1,time.time()-t_0))

    print("The value of model1 at time step {} is {}".format(t2,torch.mean(model1[ite-1](x01)).item()))
    print("The true optimal quadratic is {}".format(opt_quad().item()))
    # print("The  relative percentage error is {}: ".format((torch.abs((torch.mean(model1[ite-1](x01)))-opt_quad())).item()/torch.abs(model1[ite-1](x01)).item()))
    # index+=1


    optimizer_2=opt2(ite,t1,t2)
    for epoch in range(num_epoch2):
    # for epoch in range(100):
      t_2=time.time()
      delta_w = torch.randn(size=[num_sample, dim, num_time_interval]).to(device) * sqrt_delta_t
      # x_sample = torch.zeros([num_sample,dim, num_time_interval + 1])
      # x_sample[:, :, 0] = torch.zeros([num_sample, dim]) * x_init

      x_new,delta_w_new=data_generator2(ite,t1,t2,delta_w)
      my_index2=np.arange(x_new.shape[0])
      total_batch2=int((x_new.shape[0]/batch_size))
      for batch in range(total_batch2):
        if batch==total_batch2-1:
              temp_index=my_index2[batch*batch_size : ]
        else:
              temp_index=my_index2[batch*batch_size : batch*batch_size + batch_size]
        data2=x_new[temp_index,:]
        delta_w2=delta_w_new[temp_index,:]
        optimizer_2.zero_grad()
        loss2=loss_fn2(ite,data2.to(device),delta_w2.to(device))
        loss2.backward()
        optimizer_2.step()
      loss_tmp2.append(loss2.item())
      loss_delta2 = loss2.item() - last_loss2
      last_loss2 = loss2.item()
      if epoch %10 == 0:
        print("Loss function 2 at epoch {:.0f} is {:.12e}  |  Loss delta: {}   |    Training time: {:.5f}s".format(index*(num_epoch2)+epoch, loss_delta2,loss2.item(), time.time()-t_2))
        # print("Total time for training {:.0f} epochs is {:.4e}s".format(index*(num_epoch1)+epoch+1,time.time()-t_0))
    index+=1

    print("The value of modely2 at time step {} is {}".format(t1,modely2[t1](x0).item()))
    print("The theoretical solution is {}".format(V1(t_steps[t1],start_list[ite-1]+1).item()))
    print("The  relative percentage error is {}: ".format(torch.abs(modely2[t1](x0)-V1(t_steps[t1],start_list[ite-1]+1)).item()/torch.abs(modely2[t1](x0)).item()))
  model1results.append(model1[ite-1](x0))
  modely2results.append(modely2[t1](x0))
print(model1results)
print(modely2results)
print("The average value of {} independent runs of modely2 at time step {} is {}".format(num_runs,t1,torch.mean(torch.tensor(model1results))))
print("The average value of {} independent runs of modely2 at time step {} is {}".format(num_runs,t1,torch.mean(torch.tensor(modely2results))))
print("The training takes {:.5f} seconds.".format(time.time()-t1))

This is 1th run
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]], device='cuda:0')
At iteration 2:
5
9
Loss function 1 at epoch 0 is 2.240188041469e-05  |  Loss delta: 2.2401880414690822e-05   |    Training time: 14.84069s
Loss function 1 at epoch 10 is 2.496941320373e-09  |  Loss delta: 2.823869493795428e-08   |    Training time: 14.52255s
Loss function 1 at epoch 20 is 1.692157525213e-10  |  Loss delta: 1.2270406912762155e-08   |    Training time: 14.61558s
Loss function 1 at epoch 30 is -1.330624499474e-11  |  Loss delta: 1.9495642877842556e-09   |    Training time: 14.58236s
Loss function 1 at epoch 40 is -7.924999545494e-11  |  Loss delta: 4.3705505881064255e-10   |    Training time: 14.57955s
Loss function 1 at epoch 50 is -1.131859467263e-10  |  Loss delta: 2.0173689108116122e-10   |    Training time: 14.60033s
Loss function 1 at epoch 60 is -1.844058239442e-11  |  Loss delta: 1.5262180408370796e-10   |    Training time: 14.34933s
Loss function 1 at epoch 70 is -6.121932127900e

In [ ]:
  print("The value of model1 at time step {} is {}".format(t2,torch.mean(model1[ite-1](x01)).item()))
  print("The true optimal quadratic is {}".format(opt_quad().item()))
  # print("The  relative percentage error is {}: ".format((torch.abs((torch.mean(model1[ite-1](x01)-opt_quad())).item())))

The value of model1 at time step 4 is 8.222860336303711
The true optimal quadratic is 1.9595918655395508


In [ ]:
print(opt_quad())

tensor([1.9596], device='cuda:0')


# Test

In [ ]:
x0=torch.ones([1,dim]).to(device)+4   #our testing region is [4,6] so x0=5
print(x0)
print(x0.shape)

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]], device='cuda:0')
torch.Size([1, 10])


In [ ]:
bbb = torch.stack([torch.rand(50)+5 for i in range(dim)],dim=1)  #50 randomly generated points for testing
print(bbb.shape)
print(bbb[:,0])
ccc=modely2[0](bbb.to(device))  #evaluate these 50 random points using modely2 at time step 0
print(ccc)
ddd=V1(0,bbb[:,0].to(device))   #evaluate these 50 random point using true value function
print(ddd)
eee=torch.mean(torch.square(ccc.flatten()-ddd))  #take square difference between true and approximated values
print(eee)
# print(V1(t_steps[t1],5.3743))
# print(modely2[0](x0))

torch.Size([50, 10])
tensor([5.5818, 5.5383, 5.9696, 5.0786, 5.4429, 5.3071, 5.8215, 5.2751, 5.0937,
        5.7772, 5.7208, 5.3802, 5.0397, 5.2278, 5.0029, 5.3253, 5.2268, 5.0811,
        5.5271, 5.7614, 5.6169, 5.8119, 5.7462, 5.0296, 5.0745, 5.9486, 5.3999,
        5.3581, 5.9133, 5.2910, 5.7718, 5.7537, 5.6673, 5.1418, 5.3531, 5.6126,
        5.2714, 5.7668, 5.6234, 5.3635, 5.6950, 5.9439, 5.4636, 5.5131, 5.7722,
        5.5309, 5.8349, 5.5721, 5.7536, 5.2846])
tensor([[[1.1444]],

        [[1.1497]],

        [[1.1393]],

        [[1.1480]],

        [[1.1540]],

        [[1.1533]],

        [[1.1487]],

        [[1.1402]],

        [[1.1436]],

        [[1.1588]],

        [[1.1471]],

        [[1.1460]],

        [[1.1366]],

        [[1.1444]],

        [[1.1393]],

        [[1.1376]],

        [[1.1395]],

        [[1.1455]],

        [[1.1553]],

        [[1.1438]],

        [[1.1423]],

        [[1.1391]],

        [[1.1578]],

        [[1.1635]],

        [[1.1470]],

     